# Crear un usuario a traves del register
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type:application/json

{
  "nombre": "paco",
  "email": "paco@example.com",
  "password": "1234",
  "edad": 30,
  "ciudad": "Madrid",
  "intereses": ["lectura", "viajar", "programación"],
  "ofertas": true,
  "role": "user"
}
###
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type:application/json

{
  "nombre": "juan",
  "email": "juan@example.com",
  "password": "123",
  "edad": 30,
  "ciudad": "Madrid",
  "intereses": ["lectura", "viajar", "programación"],
  "ofertas": true,
  "role": "admin"
}
###

# Logear al usuario
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
 "email": "juan@example.com",
 "password": "123"
}
###

# El usuario se elimina a si mismo
DELETE http://localhost:3000/api/auth/6731f2c6a011b3dc55c80820 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMxZjJjNmEwMTFiM2RjNTVjODA4MjAiLCJjaWYiOm51bGwsImlhdCI6MTczMTMyNjY2MiwiZXhwIjoxNzMxNDEzMDYyfQ.iLA2MeAAhz4_3-mx1kI07tYFNRjzMaL3YlKqL8BZZ1w
###

# Cambiar uno existente, por el mismo usuario
PATCH http://localhost:3000/api/auth/673317cbdc55d913f27b2a49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzMTdjYmRjNTVkOTEzZjI3YjJhNDkiLCJjaWYiOm51bGwsImlhdCI6MTczMTQwMTY3NSwiZXhwIjoxNzMxNDg4MDc1fQ.06I1UzpjdJN2FkskXFWUMpuDMM0PbBny-p5ApV6vOJA

{
    "nombre":"Alberto"
}
###
