# Aqui se obtienen todos los datos de la tabla tal y como estan.
GET http://localhost:3000/api/comerce HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzMTdjYmRjNTVkOTEzZjI3YjJhNDkiLCJjaWYiOm51bGwsImlhdCI6MTczMTQxMDA4OCwiZXhwIjoxNzMxNDk2NDg4fQ.N81Abgiwn7jVV_8lvTvCozqwnivQq53pDZY9410EV4A
###
    
# Obtener la lista de comercios y, opcionalmente (vía parámetro query,) ordenados por el CIF ascendentemente.
GET http://localhost:3000/api/comerce?sortBycif=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzMTdjYmRjNTVkOTEzZjI3YjJhNDkiLCJjaWYiOm51bGwsImlhdCI6MTczMjU0ODkyMywiZXhwIjoxNzMyNjM1MzIzfQ.e1xV-vjNp_iZ-7V0gn7EckiNVREeFssUFHbSbrL_4dg
###

# Obtener un comercio por su CIF
GET http://localhost:3000/api/comerce/test1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzMTdjYmRjNTVkOTEzZjI3YjJhNDkiLCJjaWYiOm51bGwsImlhdCI6MTczMjU0ODkyMywiZXhwIjoxNzMyNjM1MzIzfQ.e1xV-vjNp_iZ-7V0gn7EckiNVREeFssUFHbSbrL_4dg
###

# Crear un comercio y su token (token test 1)
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOm51bGwsImNpZiI6InRlc3QxIiwiaWF0IjoxNzMxNDEyMzk0LCJleHAiOjE3NjI5Njk5OTR9.URtTk29txJvHIbDz-8SunfO_tpUyzjOLXS7FGx9FY3Y
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOm51bGwsImNpZiI6InRlc3QyIiwiaWF0IjoxNzMwODA1NDAyLCJleHAiOjE3NjIzNjMwMDJ9.CDrpYlfOAYKgncDtX2JjnDCy0pbS1x-2UrxURUSmaWw
POST http://localhost:3000/api/comerce HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMxZjJjM2EwMTFiM2RjNTVjODA4MWUiLCJjaWYiOm51bGwsImlhdCI6MTczMjc5NDQ0MCwiZXhwIjoxNzMyODgwODQwfQ.xfVpf7PlybNf2pERnsxFSwVQ4J8qmJvo0-sG-MVc-zI

{   
    "name": "prueba33",
    "cif": "test33",
    "direccion": "test33",
    "email": "test33",
    "telefono": "test33",
    "id_web": 33 
}
###

# Modificar un comercio a partir de su CIF
PUT http://localhost:3000/api/comerce/test8 HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzMTdjYmRjNTVkOTEzZjI3YjJhNDkiLCJjaWYiOm51bGwsImlhdCI6MTczMjUyNjkwOCwiZXhwIjoxNzMyNjEzMzA4fQ.ZYd__JU6QtC82-_sLMnyQCDkgPJ7vbtZZepmtMxjSS0

{
    "name": "prueba8",
    "cif": "test8",
    "direccion": "test8",
    "email": "test8",
    "telefono": "test8",
    "id_web": 8
}
###
# Borrar un comercio a partir de su CIF
DELETE http://localhost:3000/api/comerce/test8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzMTdjYmRjNTVkOTEzZjI3YjJhNDkiLCJjaWYiOm51bGwsImlhdCI6MTczMjU0ODkyMywiZXhwIjoxNzMyNjM1MzIzfQ.e1xV-vjNp_iZ-7V0gn7EckiNVREeFssUFHbSbrL_4dg